[build]
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

# Netlify の Next.js ランタイム（自動検出されますが明示しておきます）
[[plugins]]
  package = "@netlify/plugin-nextjs"
